#define VIAL_KEYBOARD_UID {0xA3, 0x45, 0x28, 0xA1, 0xB3, 0xCF, 0x00, 0xDA}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0  }
#define VIAL_UNLOCK_COMBO_COLS { 0, 9 }

#define VIAL_COMBO_ENTRIES 32
#define VIAL_TAP_DANCE_ENTRIES 32
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define LAYER_STATE_8BIT

