/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xD3, 0x73, 0x34, 0x3F, 0x58, 0xD2, 0xE0, 0x0A}
#define VIAL_UNLOCK_COMBO_COLS { 1, 1}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 9}

//Vial limits
#define VIAL_COMBO_ENTRIES 64
#define VIAL_TAP_DANCE_ENTRIES 64
#define VIAL_KEY_OVERRIDE_ENTRIES 64
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

//RGBLIGHT Animation Settings
#define RGBLIGHT_EFFECT_KNIGHT_OFFSET 9
#define RGBLIGHT_EFFECT_KNIGHT_LED_NUM 55
#define RGBLIGHT_EFFECT_KNIGHT_LENGTH 10
#define RGBLIGHT_EFFECT_SNAKE_LENGTH 10
#define RGBLIGHT_EFFECT_SNAKE_OFFSET 9
