// RGB Light settings
#define WS2812_DI_PIN A7
#define RGBLIGHT_LED_COUNT 43
#define RGBLIGHT_DEFAULT_VAL 10
#define RGBLIGHT_LIMIT_VAL 50
#define RGBLIGHT_VAL_STEP 10
#define RGBLIGHT_DEFAULT_HUE 0
#define RGBLIGHT_DEFAULT_SAT 100
#define RGBLIGHT_DEFAULT_SPD 5

// Enable all RGB effects for VIAL control
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE

// Enable RGB layers for modifier status
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF

// combos always reference to QWERTY
#define COMBO_ONLY_FROM_LAYER 0

// combo and MT restriction logic
#define COMBO_SHOULD_TRIGGER

//#define ENCODERS_PAD { A3, A4 }